Add Makefile and Debian packaging
community-ssu/libplayback pull request #1
Opened 2017-08-20 22:04 UTC by NotKit

I'm not very familiar with Debian packaging, so I used osso-bookmark-engine as base. Tested under Devuan.

2017-08-21 06:40 UTC, pali requested changes
Hi! There are a few comments...

2017-08-21 06:40 UTC, pali commented on debian/changelog
> +libplayback (0.5-21+0m5) unstable; urgency=low
Last version in Maemo is 0_0.5-23+0m5. So you should have version higher then this.

2017-08-21 06:40 UTC, pali commented on debian/control
> +Priority: optional
Section and Priority can be removed as they are same as in Source part.

2017-08-21 06:40 UTC, pali commented on Makefile
> +	libtool --mode=link --tag=CC $(CC) $(LDFLAGS) -rpath $(libdir) -version-number 0:0:5 -o $@ $^ $(LDLIBS)
In Maemo library name is /usr/lib/libplayback-1.so.0.0.5

2017-08-21 06:40 UTC, pali commented on libplayback.pc
> +Libs: -L${libdir} -lplayback
-lplayback-1

2017-08-21 12:56 UTC, freemangordon commented
Hi and thanks for the pull request. However, it seems me and Pali got used to linux kernel ML review process and we are a bit picky :), so please, fix what Pali has requested and make a new pull request if not a problem.

Also, if you didn't already do it - you can reuse some parts (like .pc file and entries in debian/control etc.) from the binary packages in maemo - http://repository.maemo.org/pool/fremantle/nokia-binaries/4bc37c7c77ebe90177c050b805a8dc79/nokia-binaries/libp/libplayback/

2017-08-21 14:43 UTC, NotKit commented on debian/control
> +Priority: optional
Should Section be removed for -dev and -dbg packages as well? Source part has "Section: libs". I checked Maemo binary package, it has "Section: libdevel" for -dev.

2017-08-21 14:46 UTC, pali commented on debian/control
> +Priority: optional
If Section or Priority is not specified in Package part, then it is automatically taken from the Source part. So it does not make sense to re-define Section or Priority in Package part to same value.

I would say, that we should match what Maemo binaries have (if values are not bogus).

2017-08-21 14:48 UTC, pali commented on debian/control
> +Depends: libplayback-1-0
(= ${binary:Version})

2017-08-21 14:48 UTC, pali commented on debian/control
> +Maintainer: Ivaylo Dimitrov <ivo.g.dimitrov.75@gmail.com>
If you are going to maintain this Debian packaging (we would be happy if yes :-)) then fill free to put your name there.

2017-08-27 19:45 UTC, pali approved these changes

2017-08-30 05:36 UTC, merged